Change $ to jQuery to prevent from $ being overridden.
Sometimes $ has been overridden, so the error `$ is not a function` happened.
This commit should fix this kind of error:

```
/home/m157q/github/2dg/index.js:31
        var code = $("script").last().text()
                   ^

TypeError: $ is not a function
    at Object.callback (/home/m157q/github/2dg/index.js:31:20)
    at Crawler._onContent
(/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:461:17)
    at Request._callback
(/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:351:18)
    at Request.self.callback
(/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:236:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous>
(/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1142:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous>
(/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1096:12)
```